import { type Metadata } from 'next'
import { ClerkProvider, useUser } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import RegisterUser from '@/components/RegisterUser'
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider
            afterSignInUrl="/redirect-after-signin"
            afterSignUpUrl="/redirect-after-signin"
        >
            <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {/* Only render RegisterUser on /onboarding */}
                {typeof window !== 'undefined' && window.location.pathname === '/onboarding' && (
                    <RegisterUser />
                )}
                <main>{children}</main>
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    )
}
